---
# steam methane reformaer algorithm config
smrConfig:
  smrPopSize: 50
  smrGenSize: 50
  smrMovingAverage: 10
  smrMutationProbability: 2

# Reformer material balance algorithm config
mbConfig:
  mbPopSize: 50
  mbGenSize: 50
  mbMovingAverage: 10
  mbMutationProbability: 2

standardPressure: 1.01325
flareGasComposition:
  ch4: 100
  c2h6: 0
  c3h8: 0
  i-c4: 0
  n-c4: 0
  i-c5: 0
  n-c5: 0
  i-c6: 0
  n-c6: 0
  h2: 0
  n2: 0
  co2: 0

traitBoundaries:
  # unit = bars
  pressureLowerbound: 20 
  pressureUpperbound: 30
  # unit = kelvin
  temperatureLowerbound: 600 
  temperatureUpperbound: 850
  # to negate coke formation
  steamCarbonRatioLowerbound: 2 
  steamCarbonRatioUpperbound: 8

outputFile: genalgo-results.txt